In [ ]:
from ValueIteration import ValueIteration, RollOutValueIteration

N = 25
M = (5, 5)
K = 100
n_episodes=500
eps = 0.0
eps_decay=0.9999

agent = RollOutValueIteration(N, M, K, n_episodes, eps, eps_decay)
agent.train()

Episode: 0/500 Cost: -4613.9400000000005
0.0
Episode: 1/500 Cost: -4301.28
0.0
Episode: 2/500 Cost: -4087.7
0.0
Episode: 3/500 Cost: -3812.5400000000004
0.0
Episode: 4/500 Cost: -3800.659999999998
0.0
Episode: 5/500 Cost: -3654.0800000000004
0.0
Episode: 6/500 Cost: -3638.14
0.0
Episode: 7/500 Cost: -3711.4400000000005
0.0
Episode: 8/500 Cost: -3780.360000000001
0.0
Episode: 9/500 Cost: -3672.3600000000006
0.0
Episode: 10/500 Cost: -3659.3600000000006
0.0
Episode: 11/500 Cost: -3689.2
0.0
Episode: 12/500 Cost: -3602.5399999999995
0.0
Episode: 13/500 Cost: -3631.0000000000005
0.0
Episode: 14/500 Cost: -3649.26
0.0
Episode: 15/500 Cost: -3671.38
0.0
Episode: 16/500 Cost: -3643.2199999999993
0.0
Episode: 17/500 Cost: -3532.7799999999997
0.0
Episode: 18/500 Cost: -3802.0399999999995
0.0
Episode: 19/500 Cost: -3726.3599999999997
0.0
Episode: 20/500 Cost: -3696.119999999999
0.0
Episode: 21/500 Cost: -3610.499999999999
0.0
Episode: 22/500 Cost: -3692.0599999999995
0.0
Episode: 23/500 Cost: -3

KeyboardInterrupt: 

In [ ]:
agent.evaluate()

Initial Map:[[18 16  8  6 19]
 [14 10 25 24 17]
 [ 9 15 22 23  1]
 [21  5  4 12  2]
 [13 20  7  3 11]], P_Order: [0.0196078431372549, 0.058823529411764705, 0.09803921568627451, 0.13725490196078433, 0.17647058823529413, 0.21568627450980393, 0.2549019607843137, 0.29411764705882354, 0.3333333333333333, 0.37254901960784315, 0.4117647058823529, 0.45098039215686275, 0.49019607843137253, 0.5294117647058824, 0.5686274509803921, 0.6078431372549019, 0.6470588235294118, 0.6862745098039216, 0.7254901960784313, 0.7647058823529411, 0.803921568627451, 0.8431372549019608, 0.8823529411764706, 0.9215686274509803, 0.9607843137254902]
action: 177 Cost: -88.94000000000001, Map:[[18 16  8  6 19]
 [14 10 25 24 17]
 [23 15 22  9  1]
 [21  5  4 12  2]
 [13 20  7  3 11]]
action: 189 Cost: -85.58000000000001, Map:[[18 16  8  6 19]
 [14 20 25 24 17]
 [23 15 22  9  1]
 [21  5  4 12  2]
 [13 10  7  3 11]]
action: 243 Cost: -83.56, Map:[[18 16  8  6 19]
 [24 20 25 14 17]
 [23 15 22  9  1]
 [21  5  4 12  2]
 [13 10  

In [ ]:
import torch
# Saving Model
torch.save({
            'p_vector': agent.env.env.order_p,
            'model_state_dict': agent.ffnn_v.state_dict(),
            'N': N,
            'M': M,
            'K': K,
            }, "ffnn_v.pt")


In [ ]:
checkpoint = torch.load("ffnn_v.pt")

In [ ]:
checkpoint.keys()

dict_keys(['p_vector', 'model_state_dict', 'N', 'M', 'K'])